[package]

name = "shred"
version = "1.1.0"
authors = ["Michael Rosenberg <42micro@gmail.com>"]

[[bin]]
name = "shred"
path = "shred.rs"

[profile.release]
opt-level = 3
lto = true

[dependencies]
getopts = "0.2.10"
rand = "0.3.8"
